name: Daily Joke Generator

on:
  # Run daily at 12:00 UTC
  schedule:
    - cron: '0 12 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Generate joke and update README
        run: |
          # Generate a new joke
          JOKE=$(python generate_joke.py)
          
          # Remove the last two lines from README.md
          head -n -2 README.md > temp_readme.md
          
          # Add the new joke with the required prefix
          echo "The following joke was generated daily by a hook written entirely by Copilot." >> temp_readme.md
          echo "$JOKE" >> temp_readme.md
          
          # Replace the original README.md
          mv temp_readme.md README.md
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update README with daily joke - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push
          fi
