name: Daily Joke Update

on:
  # Run daily at 12:00 UTC
  schedule:
    - cron: '0 12 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate joke
      id: joke
      run: |
        JOKE=$(python generate_joke.py)
        echo "joke=$JOKE" >> $GITHUB_OUTPUT
    
    - name: Update README.md
      run: |
        # Remove the last line from README.md
        head -n -1 README.md > temp_readme.md
        mv temp_readme.md README.md
        
        # Append the new joke with the required prefix
        echo "" >> README.md
        echo "The following joke was generated daily by a SLM." >> README.md
        echo "${{ steps.joke.outputs.joke }}" >> README.md
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Daily joke update - $(date +'%Y-%m-%d')"
          git push
        fi